### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by ubaumann**
Tests will come in handy for developing the template. This is a fist idea, and I am happy to discuss.
What do you think?

### CODE REVIEW

**Comment by tbotnz** [comment]
@ubaumann, tests are a great idea! Personally, i  was hoping to reach a reasonable level of adoption & stability ( yet to be defined ) of the data model prior to implementing.  I dont object to writing test yet if you are volunteering :)

**Comment by ubaumann** [comment]
First I was also thinking I would like to have a basic config in a basic state but it happened once or twice a change I wanted to make broke other parts so I was thinking some basic test could help a lot. Of course every time the data structure changes the tests need to be changed but it will help to be sure the change is good. Also some features can have different cli styles.

You like the idea with yaml file or you would prefer something else? Everything can be changed later. Hopefully more people will contribute and actually use it.

**Comment by tbotnz** [comment]
@ubaumann. Whilst the YAML file wouldn't be my first choice its better than no testing 👍 we can replace it later if it gets annoying. Lmk when you want to merge the PR.

**Comment by ubaumann** [comment]
Sorry I was in vacation and forgot my notebooks at home.
I guess we can merge it and start refactoring the template little by little

**Pull request merged**
